### ISSUE TITLE
Startsida funktioner

### ISSUE THREAD

**Issue by Lucaspers** [juliamattson/feetish#6]
Webbsidan skall ha en startsida med minst följande funktioner:  
- Ett bildspel som presenterar aktuella kampanjer.  
- En kampanj kan representeras av en kategori med produkter, eller en rabattkod som ger rabatt.  
- Bildspelet kan vara en del i ert tema eller skapas med ett färdigt bildspelsplugin.

**Comment by fridaedda** [comment]
Nu ligger bildspelet på Startsidan/Hem
